export const POSITIVE = [
  'interior design',
  'detailed (white background )',
  'atmospheric',
  'canon eos c 3 0 0',
  'ƒ 1. 8',
  '3 5 mm',
  '8 k',
];

export const NEGATIVE = [
  '(((stock photo)))',
  '((((ugly))))',
  '(((duplicate)))',
  '((morbid))',
  '((mutilated))',
  '[out of frame]',
  'extra fingers',
  'mutated hands',
  '((poorly drawn hands))',
  '((poorly drawn face))',
  '(((mutation)))',
  '(((deformed)))',
  '((ugly))',
  'blurry',
  '((bad anatomy))',
  '(((bad proportions)))',
  '((extra limbs))',
  'cloned face',
  '(((disfigured)))',
  'out of frame',
  'ugly',
  'extra limbs',
  '(bad anatomy)',
  'gross proportions',
  '(malformed limbs)',
  '((missing arms))',
  '((missing legs))',
  '(((extra arms)))',
  '(((extra legs)))',
  'mutated hands',
  '(fused fingers)',
  '(too many fingers)',
  '(((long neck)))',
  'grayscale',
  'black and white',
  '(((bad composition)))',
  '((((stock photo))))',
];
